# THIS FILE IS AUTOMATICALLY GENERATED
# Project: H:\Group3\PacMan-Robot\301_Group_3_Software\PSOC_code_T1\Workspace01\Design01.cydsn\Design01.cyprj
# Date: Thu, 10 Oct 2019 01:44:05 GMT
#set_units -time ns
create_clock -name {ADC_SAR_1_theACLK(routed)} -period 83.333333333333329 -waveform {0 41.6666666666667} [list [get_pins {ClockBlock/dclk_1}]]
create_clock -name {ADC_SAR_Seq_1_IntClock(routed)} -period 541.66666666666663 -waveform {0 270.833333333333} [list [get_pins {ClockBlock/dclk_3}]]
create_clock -name {CyILO} -period 10000 -waveform {0 5000} [list [get_pins {ClockBlock/ilo}] [get_pins {ClockBlock/clk_100k}] [get_pins {ClockBlock/clk_1k}] [get_pins {ClockBlock/clk_32k}]]
create_clock -name {CyIMO} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/imo}]]
create_clock -name {CyPLL_OUT} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/pllout}]]
create_clock -name {CyMASTER_CLK} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/clk_sync}]]
create_generated_clock -name {CyBUS_CLK} -source [get_pins {ClockBlock/clk_sync}] -edges {1 2 3} [list [get_pins {ClockBlock/clk_bus_glb}]]
create_generated_clock -name {Clock_2} -source [get_pins {ClockBlock/clk_sync}] -edges {1 3 5} [list [get_pins {ClockBlock/dclk_glb_0}]]
create_generated_clock -name {ADC_SAR_1_theACLK} -source [get_pins {ClockBlock/clk_sync}] -edges {1 3 5} [list [get_pins {ClockBlock/dclk_glb_1}]]
create_generated_clock -name {Clock_1} -source [get_pins {ClockBlock/clk_sync}] -edges {1 5 11} -nominal_period 208.33333333333331 [list [get_pins {ClockBlock/dclk_glb_2}]]
create_generated_clock -name {ADC_SAR_Seq_1_IntClock} -source [get_pins {ClockBlock/clk_sync}] -edges {1 13 27} -nominal_period 541.66666666666663 [list [get_pins {ClockBlock/dclk_glb_3}]]
create_generated_clock -name {UART_1_IntClock} -source [get_pins {ClockBlock/clk_sync}] -edges {1 53 105} -nominal_period 2166.6666666666665 [list [get_pins {ClockBlock/dclk_glb_4}]]


# Component constraints for H:\Group3\PacMan-Robot\301_Group_3_Software\PSOC_code_T1\Workspace01\Design01.cydsn\TopDesign\TopDesign.cysch
# Project: H:\Group3\PacMan-Robot\301_Group_3_Software\PSOC_code_T1\Workspace01\Design01.cydsn\Design01.cyprj
# Date: Thu, 10 Oct 2019 01:43:48 GMT
