/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  3.3 CP3
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2016 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "LED_aliases.h"
#include "LED.h"
#include "Sensor1_aliases.h"
#include "Sensor1.h"
#include "PWM_1.h"
#include "Clock_1.h"
#include "PW1_1_aliases.h"
#include "PW1_1.h"
#include "PW1_2_aliases.h"
#include "PW1_2.h"
#include "chA1_aliases.h"
#include "chA1.h"
#include "chA2_aliases.h"
#include "chA2.h"
#include "PWM_2.h"
#include "PW2_1_aliases.h"
#include "PW2_1.h"
#include "PW2_2_aliases.h"
#include "PW2_2.h"
#include "Timer_1.h"
#include "QuadDec_1.h"
#include "QuadDec_2.h"
#include "chB1_aliases.h"
#include "chB1.h"
#include "isr_1.h"
#include "chB2_aliases.h"
#include "chB2.h"
#include "Clock_2.h"
#include "ADC_SAR_Seq_1.h"
#include "Sensor2_aliases.h"
#include "Sensor2.h"
#include "Sensor3_aliases.h"
#include "Sensor3.h"
#include "ADC_SAR_1.h"
#include "Sensor4_aliases.h"
#include "Sensor4.h"
#include "Sensor5_aliases.h"
#include "Sensor5.h"
#include "UART_1.h"
#include "UART_2.h"
#include "QuadDec_1_Cnt8.h"
#include "QuadDec_2_Cnt8.h"
#include "ADC_SAR_Seq_1_SAR.h"
#include "ADC_SAR_Seq_1_IntClock.h"
#include "ADC_SAR_Seq_1_TempBuf_dma.h"
#include "ADC_SAR_Seq_1_FinalBuf_dma.h"
#include "ADC_SAR_Seq_1_IRQ.h"
#include "ADC_SAR_1_IRQ.h"
#include "ADC_SAR_1_theACLK.h"
#include "ADC_SAR_1_ExtVref_aliases.h"
#include "ADC_SAR_1_ExtVref.h"
#include "UART_1_IntClock.h"
#include "UART_2_IntClock.h"
#include "ADC_SAR_Seq_1_SAR_ExtVref_aliases.h"
#include "ADC_SAR_Seq_1_SAR_ExtVref.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"

/*[]*/

